
'''
The goal of visualization is to understand the distribution of the different variables of our data:
Open, Close, High, Low, Volume.
This will inform the model architecture i.e: 
Will the model learn to predict Gaussian distributions or Poisson distributions?
The covariate variables are arranged as: 
[month,day,open,low,high,close,volume, company name]
'''
import tqdm
import numpy as np
import pandas as pd
from pathlib import Path
import sys
import plotly.express as px

sys.path.insert(0,str(Path(__file__).parent.parent))
from constants import DATA_PATH, TARGET_COMPANIES, COMPANY_DATA_PATH

def save_plot_npy(data, covariate_column_index, out_file):
  column = np.reshape(test_data[:,:,covariate_column_index],(-1,1))
  df = pd.DataFrame(data=column)
  fig = px.histogram(x=df[0],range_x=[df.min(),df.max()])
  fig.write_image(DATA_PATH+"/"+out_file)

def save_plot_df(df,covariate_column_index,out_file):
  fig = px.histogram(x=df[covariate_column_index],range_x=[df.min(),df.max()])
  fig.write_image(DATA_PATH+"/"+out_file)


if __name__ == '__main__':
  '''
  The covariate variables are arranged as: 
  [open,volume,...]
  '''
  
  for company in tqdm.tqdm(TARGET_COMPANIES):
    df = pd.read_csv(COMPANY_DATA_PATH+'/'+company+'.csv')
    save_plot_df(df,'open','open_'+company+'.png')
    save_plot_df(df,'volume','volume_'+company+'.png')
  
  
  
  '''
    use this when you want to plot from the numpy generated by company_data.py
  
  '''
  '''
  indices_and_file_names = [(0,"open.png"),(1,"volume.png")]
  test_data = np.load(DATA_PATH + '/stock_inputs.npy', allow_pickle=True)
  print(test_data.shape)
  for index, file_name in tqdm.tqdm(indices_and_file_names):
    save_plot_npy(test_data,index,file_name)
  '''